### ISSUE TITLE
'pip install uncommitted'  errors out

### ISSUE THREAD

**Issue by DaniSpringer** [brandon-rhodes/uncommitted#34] opened 2019-05-09 17:48 UTC
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting uncommitted
Using cached https://files.pythonhosted.org/packages/6a/47/a51d555349bc67c60c155c566d5edad670f61fcae01d2b58dafdcf894b79/uncommitted-2.1.tar.gz
Installing collected packages: uncommitted
Running setup.py install for uncommitted ... error
ERROR: Complete output from command /usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/3k/6s8r4w9910bfl8c4tzspn9gw0000gn/T/pip-install-14hWWQ/uncommitted/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3k/6s8r4w9910bfl8c4tzspn9gw0000gn/T/pip-record-QbXFYX/install-record.txt --single-version-externally-managed --compile:
ERROR: running install
running build
running build_py
creating build
creating build/lib
creating build/lib/uncommitted
copying uncommitted/command.py -> build/lib/uncommitted
copying uncommitted/__init__.py -> build/lib/uncommitted
copying uncommitted/test_unit.py -> build/lib/uncommitted
copying uncommitted/test_integration.py -> build/lib/uncommitted
running install_lib
creating /Library/Python/2.7/site-packages/uncommitted
error: could not create '/Library/Python/2.7/site-packages/uncommitted': Permission denied
----------------------------------------
ERROR: Command "/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/3k/6s8r4w9910bfl8c4tzspn9gw0000gn/T/pip-install-14hWWQ/uncommitted/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3k/6s8r4w9910bfl8c4tzspn9gw0000gn/T/pip-record-QbXFYX/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/3k/6s8r4w9910bfl8c4tzspn9gw0000gn/T/pip-install-14hWWQ/uncommitted/`

**Comment by brandon-rhodes** [comment] 2019-05-17 01:44
Could you try editing your text and using GitHub markup to delimit the text that you typed as a command, and the text that came back, so they both display as typewriter text? That will help me reproduce the issue; please also include exactly the steps I should take with what kind of machine to reproduce the error. I can't quite tell from what's here. Thanks!

**Comment by DaniSpringer** [comment] 2019-05-17 03:46
Edited.
MacBook Air
macOS 10.14.5
Terminal
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Command ran: `pip install uncommitted`

**Comment by brandon-rhodes** [comment] 2019-05-25 22:17
(Thanks for your patience, I've been busy this past week or two!) It looks like you are trying to install the package system-wide on your Mac but it is not letting you, but is giving you a `Permission denied` instead. Try installing some other package like maybe Bottle or Django. If it also gives the same error, then your problem is with installing Python packages in general, and you'll want to go read a guide to how to get Python packages installed on your Mac. (I use Linux.) But if only uncommitted gives the error, then we can look further for a specific cause!

**Comment by brandon-rhodes** [comment] 2020-04-08 14:09
As this has been open 10 months without a resolution, I'm going to temporarily close it pending more information from you. If you do have more questions, feel free to ask them in additional comments and I'll try to respond. Thanks!

**Closed by brandon-rhodes** 2020-04-08 14:09 UTC
